# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e318b93c9de2a285fe20f481788ceb28d9ef2a01809106d73e5eeca4f1909f86660bcf3afd45825ca77dbe7b96a6433b28db60dc911b6375fa519beec82d0c1

test:
  secret_key_base: 263a2f973b25a701651e5527a2219decffe8c58abf5d25a36a126852bca2dc121ad37389e32d5885c613a09ffb829f9a9d7c6c4542539429e038618e7334eb7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
